### PR TITLE
Move traceresponse processing to processing model

### LINKED ISSUE #445: Move response header Returning the traceresponse Field to non-normative processing section.
Move response header `Returning the traceresponse Field` to non-normative processing section.

>may be this paragraph would work better in request processing section which is non-formative. It sounds like an example rather than a spec. Maybe spec may only say that sampling bit returned in response header may not match the flag that was sent in the request and processing will give this example with the event that happens during the processing in the processing section.

_Originally posted by @SergeyKanzhelev in https://github.com/w3c/trace-context/pull/443#discussion_r543581108_

### PR DESCRIPTION
**Pull request by dyladan**
fixes #445

***
<a href="https://pr-preview.s3.amazonaws.com/dynatrace-oss-contrib/trace-context/pull/450.html" title="Last updated on Jan 26, 2021, 8:12 PM UTC (464b443)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/trace-context/450/5634149...dynatrace-oss-contrib:464b443.html" title="Last updated on Jan 26, 2021, 8:12 PM UTC (464b443)">Diff</a>

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]

**Review by danielkhan — APPROVED** [review]

**Comment by dyladan** [comment]
Still looking for reviews :)

**Comment by cwensel** [comment]
Changes look great. Unsure if I'm marked as an approver.

**Review by Kanwaldeep — APPROVED** [review]

**Comment by Kanwaldeep** [comment]
Seems like I'm not marked as reviewer as well.

**Review by yurishkuro — APPROVED** [review]

**Review by cwensel — APPROVED** [review]
Looks great.

**Pull request merged**
