### PR TITLE
Backport to level-1: Remove contradiction in TraceState mutations

### LINKED ISSUE #422: Contradiction in TraceState requirements
It is confusing that an updated key MUST be moved to the left, but a newly added key only SHOULD be added on the left. If you delete your key, then add your key somewhere other than the start of the list (because that requirement is only SHOULD), haven't you edited the key without moving it left? I think this is a contradiction in the spec.

_Originally posted by @dyladan in https://github.com/w3c/trace-context/pull/421#r482283902_

### PR DESCRIPTION
**Pull request by dyladan**
Backport #423 (also backport wording improvements from #421 which did not contain breaking changes /cc @arminru)

>The original contradiction:
>
>1. Modified keys MUST be moved to the left of the list
>2. Deletion is allowed
>3. New keys SHOULD be added on the left, which implies they MAY be added
>   somewhere else.
>4. Deleting a key and adding it somewhere other than the left of the
>   list breaks (1).
>
>Fixes #422

***
<a href="https://pr-preview.s3.amazonaws.com/dynatrace-oss-contrib/trace-context/pull/427.html" title="Last updated on Oct 7, 2020, 1:13 PM UTC (0d4c468)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/trace-context/427/85789a7...dynatrace-oss-contrib:0d4c468.html" title="Last updated on Oct 7, 2020, 1:13 PM UTC (0d4c468)">Diff</a>

### CODE REVIEW

**Comment by dyladan** [comment]
bump for reviews. this is just a backport of previously approved wording

**Comment by dyladan** [comment]
ping: @caribouW3 what is the official W3C policy on backporting changes to already released recommendations like this? Just want to make sure I'm not breaking any rules.

**Comment by caribouW3** [comment]
Errata management is defined in the W3C Process. 
https://www.w3.org/2020/Process-20200915/#errata

So apparently we should use
https://w3c.github.io/trace-context/errata.html

**Comment by dyladan** [comment]
@caribouW3 so if I understood that properly, #428 starts this process.

**Pull request merged**
