### PR TITLE
Add instana as known implementation

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**

### CODE REVIEW

**Review by AloisReitbauer — COMMENTED** [review]
We should also add the other vendors who have an implementations

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer as long as there will be implementation in main branch we should definitely do it. I'd suggest to start the list.

**Comment by bripkens** [comment]
The implementation doesn't contain any Instana specifics. IMHO we should have two lists:

1. Libraries that are useful when implementing TraceContext support (we all need a parser, so why not share it?). This is intended for implementers.
2. Tools / Vendors supporting TraceContext. This might come in handy for users.

**Comment by SergeyKanzhelev** [comment]
Decision was to only add implementation that conform to test suite

**Pull request closed without merging**
