### PR TITLE
Add Go to the list of implementations for Instana

### PR DESCRIPTION
**Pull request by andrewslotin**
As of [v1.13.0](https://github.com/instana/go-sensor/releases/tag/v1.13.0) Instana Go sensor has full support of W3C Trace Context out-of-the-box

### CODE REVIEW

**Review by dyladan — APPROVED** [review]

**Review by mmanciop — APPROVED** [review]

**Comment by andrewslotin** [comment]
Not sure how to proceed here. I've created a W3C account and now https://labs.w3.org/repo-manager/pr/id/w3c/trace-context/410 does not load for me 😕

**Comment by dyladan** [comment]
Loading fine for me. Wonder if it was down? You need to link your github and w3c accounts which can be done by going here https://www.w3.org/users/myprofile/connectedaccounts

**Comment by andrewslotin** [comment]
@dyladan, times out while loading https://labs.w3.org/repo-manager/api/team-contact-of in both Safari and Firefox. The GitHub account is linked now

**Comment by dyladan** [comment]
Looks like the account is linked now. Because you're not a member of the WG, the PR will have to be marked as non-substantive. I'm not sure if this is something I'm allowed to just do, or if it needs some approval. @danielkhan ?

**Comment by mtwo** [comment]
@dyladan non-substantive should be fine in this case

**Comment by mtwo** [comment]
Marked as non-substantive

**Review by mtwo — APPROVED** [review]

**Review by danielkhan — APPROVED** [review]
LGTM

**Pull request merged**
