### PR TITLE
Typo fix: s/complaint/compliant/

### PR DESCRIPTION
**Pull request by c24t**
I know this repo sees its share of complaints, but I don't think they're meant to be in the spec.

cc @SergeyKanzhelev

### CODE REVIEW

**Review by dyladan — APPROVED** [review]

**Comment by dyladan** [comment]
@c24t looks like you need to link your w3 account

**Comment by c24t** [comment]
I linked the account, but it looks like https://labs.w3.org/repo-manager/pr/id/w3c/trace-context/372 is hanging. In any case this is a non-substantial PR.

**Comment by plehegar** [comment]
Marked as non substantive for IPR from ash-nazg.

**Review by plehegar — APPROVED** [review]

**Review by mtwo — APPROVED** [review]
But what if we have compliant complaints? :)

**Review by SergeyKanzhelev — APPROVED** [review]

**Pull request merged**
