### PR TITLE
Restructure: placeholders for other protocols

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
As discussed [yesterday](https://github.com/w3c/distributed-tracing-wg/blob/master/meeting_notes/2018-12-04.md) I'm making some folders restructure to allow to add other protocols. Specifically - AMQP and Binary.

@plehegar suggested to structure it as an extension specs so we will not block the HTTP spec on discussions of AMQP, Binary and any other spec.

This is a very first and disruptive restructure to demonstrate how the structure may look like. Basically - two more report `html` files with the separate abstracts and sotd (Status of This Document) sections.

As the next step I plan to move definitions of `Trace-id`, `parent-id` and such to the `spec/11-fields-semantics.md` section (currently empty). This section will be defined right after the Overview. This way http section as well as AMQP and binary extensions will be able to refer to those fields semantics.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/trace-context/pull/213.html" title="Last updated on Dec 5, 2018, 7:10 PM GMT (3e2303c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/trace-context/213/ea4923d...3e2303c.html" title="Last updated on Dec 5, 2018, 7:10 PM GMT (3e2303c)">Diff</a>

### CODE REVIEW

**Review by mtwo — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
@plehegar please let me know if this structure is un-traditional and there are better alternatives. I'll merge this PR and will do further work in separate PRs

**Review by AloisReitbauer — COMMENTED** [review]
I would not structure it this way. I rather have other protocol definition in a separate document referencing the actual standard.

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer please elaborate. This structure creates multiple docs -

- Main doc with http definition https://w3c.github.io/trace-context/
- Binary https://w3c.github.io/trace-context/extension-binary.html
- AMQP https://w3c.github.io/trace-context/extension-amqp.html

So we can close on the first one and two others will be coming later as extensions.

**Comment by AloisReitbauer** [comment]
Ok, this makes sense. My point was to declare a dependency in the references sections and then we are good.

**Comment by SergeyKanzhelev** [comment]
great. Can you please review this one: https://github.com/w3c/trace-context/pull/214 Basically semantics of fields is moving up so it can be referenced from other protocols implementation

**Pull request merged**
