### PR TITLE
add comment that repository was moved

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by tylerbenson** [comment]
It's a shame we couldn't migrate the repo on Github's side like @wu-sheng did with Skywalking.... Was that option already considered and decided against for some reason?

**Comment by wu-sheng** [comment]
@tylerbenson The tranditional ASF community people just accept the way. :) Maybe w3c people are even more tranditional? ;P

**Comment by SergeyKanzhelev** [comment]
@tylerbenson this would be ideal. I just sent another e-mail. Now to W3C support.

**Comment by SergeyKanzhelev** [comment]
Not relevant any more

**Pull request closed without merging**
