### PR TITLE
Create working version again

### PR DESCRIPTION
**Pull request by AloisReitbauer**
Trying to fix the current problem with broken spec

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
This is an empty PR?

**Comment by AloisReitbauer** [comment]
Weird.

**Comment by cwe1ss** [comment]
Maybe this is using https://github.com/kelseyhightower/nocode ? :smile:

**Comment by SergeyKanzhelev** [comment]
I think you meant this: https://github.com/w3c/distributed-tracing/pull/85 Please reopen if not

**Pull request closed without merging**
