### PR TITLE
[WIP] Changed abstract to define the problem we are solving and the proposed solution

### PR DESCRIPTION
**Pull request by AloisReitbauer**
Still WIP. Create PR for communication

addresses #203

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
> Still WIP. Create PR for communication

please let know when it's ready for review

**Comment by SergeyKanzhelev** [comment]
Any updates on this PR?

**Comment by SergeyKanzhelev** [comment]
Some feedback - I'd suggest to keep a reference to other specs in the abstract. Something like 

> To correlate events between components, these components need to exchange and store a piece of information called context. Typically context consists of an originating event identifier, an originating component identity and other event properties. This specification describes how event identifiers should be formed and used to correlate events. Other specifications cover context propagation aspects like user-defined properties propagation, storage format, etc.

So specification will be scoped to a specific problem.

**Comment by SergeyKanzhelev** [comment]
I think the minimum we need to make to address #203 is to make it clear that correlation context is not part of this spec. This sentence:

> Correlation context carries user-defined properties.

All other wording updates may happen in the next milestone

**Comment by danielkhan** [comment]
Closed in favor of https://github.com/w3c/trace-context/pull/259

**Pull request closed without merging**
